services:
  db:
    image: postgres
    env_file:
      - docker.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/initdb:/docker-entrypoint-initdb.d
      