services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - docker.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    command: ./mvnw spring-boot:run -Dmaven.test.skip=true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NODE_ENV=development      # TODO: Remove this line in production
      - WATCHPACK_POLLING=true    # TODO: Remove this line in production
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres
    restart: always
    env_file:
      - docker.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: