version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/g1t3
      - SPRING_DATASOURCE_USERNAME=g1t3
      - SPRING_DATASOURCE_PASSWORD=g1t3
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_SHOW_SQL=true
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    command: >
      sh -c "
        while ! nc -z db 5432; do
          echo 'Waiting for database to be available...'
          sleep 1
        done
        ./mvnw spring-boot:run -Dmaven.test.skip=true
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_SPRINGBOOT_API_URL=http://backend:8080
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm start

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=g1t3
      - POSTGRES_PASSWORD=g1t3
      - POSTGRES_DB=g1t3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: