version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - docker.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    command: ./mvnw spring-boot:run -Dmaven.test.skip=true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NODE_ENV=development      # TODO: Remove this line in production
      - WATCHPACK_POLLING=true    # TODO: Remove this line in production
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: mysql:8.0
    env_file:
      - docker.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: