services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - docker.env
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    command: >
      sh -c "
        while ! nc -z db 5432; do
          echo 'Waiting for database to be available...'
          sleep 1
        done
        echo 'Database is available, waiting 5 more seconds for full initialization...'
        sleep 5
        ./mvnw spring-boot:run -Dmaven.test.skip=true
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}
        - NEXT_PUBLIC_SPRINGBOOT_API_URL=${NEXT_PUBLIC_SPRINGBOOT_API_URL:-http://localhost:8080}
    image: yourusername/frontend:${TAG:-latest}
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}
      - NEXT_PUBLIC_SPRINGBOOT_API_URL=${NEXT_PUBLIC_SPRINGBOOT_API_URL:-http://localhost:8080}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres
    env_file:
      - docker.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./.docker/initdb:/docker-entrypoint-initdb.d

volumes:
  pgdata:
