spring:
    application:
        name: "G1-T3"

    datasource:
        url: jdbc:postgresql://localhost:5432/g1t3
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: P@ssw0rd

    jpa:
        properties:
            hibernate:
                format-sql: true
        hibernate:
            ddl-auto: create-drop
            # ddl-auto: update          # Uncomment for production
        show-sql: true
        database: postgresql