spring:
    application:
        name: 'G1-T3'

    datasource:
        url: jdbc:postgresql://localhost:5432/g1t3
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: P@ssw0rd

    jpa:
        properties:
            hibernate:
                format-sql: true
        hibernate:
            ddl-auto: update
        # show-sql: true
        database: postgresql

    mail:
        host: smtp.gmail.com
        port: 587
        username: # Insert Gmail Address
        password: # Insert Password
        protocol: smtp
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE

jwt:
    secret-key: 'b94801bb5520b2b660fe5a88c59b219366d6e3919c2630a32be2d41bc3d676de'
    expiration-time:
        authentication: 864000000
        email-verification: 8640000

password:
    policy:
        min-length: 12
        max-length: 128
        require-uppercase: true
        require-lowercase: true
        require-numbers: true
        require-special-chars: true
        lockout-attempts: 5
        lockout-duration-minutes: 30

app:
    frontend:
        url: 'http://localhost:3000'

    backend:
        url: 'http://localhost:8080'

firebase:
    credentials:
        path: '.firebase\quagmire-smu-firebase-adminsdk-7qc2z-e4839f85c5.json\'  # Insert path to private key here
    storage:
        url: 'https://firebasestorage.googleapis.com/v0/b/'
        bucket: 'quagmire-smu.appspot.com'