spring:
  application:
    name: G1-T3
  datasource:
    url: jdbc:postgresql://localhost:5432/g1t3
    username: postgres
    password: P@ssw0rd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update