# src/main/resources/application.yml
spring:
    application:
        name: 'G1-T3'

    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        driver-class-name: org.postgresql.Driver
        username: ${DB_USER}
        password: ${DB_PASSWORD}

    jpa:
        properties:
            hibernate:
                format-sql: true
        hibernate:
            ddl-auto: create-drop
        database: postgresql

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        protocol: smtp
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE

jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time:
        authentication: ${JWT_AUTH_EXPIRATION}
        email-verification: ${JWT_EMAIL_VERIFICATION_EXPIRATION}

password:
    policy:
        min-length: 12
        max-length: 128
        require-uppercase: true
        require-lowercase: true
        require-numbers: true
        require-special-chars: true
        lockout-attempts: 5
        lockout-duration-minutes: 30

app:
    frontend:
        url: ${FRONTEND_URL}
    backend:
        url: ${BACKEND_URL}

firebase:
    credentials:
        path: ${FIREBASE_CREDENTIALS_PATH}
    storage:
        url: 'https://firebasestorage.googleapis.com/v0/b/'
        bucket: ${FIREBASE_BUCKET}
