name: Frontend CI/CD

on:
  push:
    branches: [ production ]
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build
        run: |
          cd frontend
          npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL_PRODUCTION }}
          NEXT_PUBLIC_SPRINGBOOT_API_URL: ${{ secrets.NEXT_PUBLIC_SPRINGBOOT_API_URL_PRODUCTION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push frontend image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: frontend-${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update ECS service
        run: |
          # Get the current task definition
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ${{ secrets.FRONTEND_ECS_TASK_DEFINITION }})
          
          # Extract the necessary parts of the task definition
          FAMILY=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.family')
          NETWORK_MODE=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.networkMode')
          TASK_ROLE_ARN=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.taskRoleArn')
          EXECUTION_ROLE_ARN=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.executionRoleArn')
          CPU=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.cpu')
          MEMORY=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.memory')
          
          # Update the image in the container definitions
          CONTAINER_DEFINITIONS=$(echo $TASK_DEFINITION | jq '.taskDefinition.containerDefinitions')
          NEW_CONTAINER_DEFINITIONS=$(echo $CONTAINER_DEFINITIONS | jq --arg IMAGE "${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:frontend-${{ github.sha }}" '.[0].image = $IMAGE')
          
          # Create the new task definition
          NEW_TASK_DEFINITION=$(jq -n \
            --arg family "$FAMILY" \
            --arg networkMode "$NETWORK_MODE" \
            --arg taskRoleArn "$TASK_ROLE_ARN" \
            --arg executionRoleArn "$EXECUTION_ROLE_ARN" \
            --arg cpu "$CPU" \
            --arg memory "$MEMORY" \
            --argjson containerDefinitions "$NEW_CONTAINER_DEFINITIONS" \
            '{
              family: $family,
              networkMode: $networkMode,
              taskRoleArn: $taskRoleArn,
              executionRoleArn: $executionRoleArn,
              cpu: $cpu,
              memory: $memory,
              containerDefinitions: $containerDefinitions
            }')
          
          # Register the new task definition
          NEW_TASK_DEFINITION_ARN=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION" --query 'taskDefinition.taskDefinitionArn' --output text)
          
          # Update the service with the new task definition
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service ${{ secrets.FRONTEND_ECS_SERVICE_NAME }} --task-definition $NEW_TASK_DEFINITION_ARN --force-new-deployment

      - name: Wait for ECS service stability
        run: |
          aws ecs wait services-stable --cluster ${{ secrets.ECS_CLUSTER_NAME }} --services ${{ secrets.FRONTEND_ECS_SERVICE_NAME }}